apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: couchbase-cluster
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: production
  source:
    path: couchbase-cluster/base
    repoURL: https://github.com/mcouliba/couchbase-demo
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true

